close all
clear all
clc

L0 = 3; % optimal muscle length [cm]

density = 1.06; % muscle density [g/cm^3]
mass = 0.0055; % muscle mass [kg]
PCSA = (mass*1000)/(density*L0); % PCSA of muscle
sigma = 22.4; % specific tension
F0 = PCSA*sigma;
N_MU = 180; % number of motor units
i_MU = 1:N_MU; % index for motor units

% Peak tetanus parameter
RP_MU = 25; %range of peak tension across motor untis in unit of fold
b_MU = log(RP_MU)/N_MU; %coefficient to establish a range of twich force values
P_MU = exp(b_MU*i_MU); %force generated by a motor unit as a function of its recruitment threshold
PTi = P_MU./sum(P_MU)*F0;

figure(1)
plot(i_MU,PTi,'LineWidth',2,'Color',[0.078,0,0.831])
xlabel('Motor Unit #','FontSize',14)
ylabel('Peak Tetanic Tension (N)','FontSize',14)
title(['F_0 = ' num2str(F0) ' (N)'],'FontSize',14)
