%==========================================================================
% check_MU_LO_sweep.m
% Author: Akira Nagamori
% Last update: 6/23/2020
% Descriptions: 
%   Check model characteristics (contraction time, twitch-tetanus ratio,
%   etc) of temporary model parameter sets generated by build_MU_LO_sweep
%==========================================================================

close all
clc
clear all

code_folder = '/Users/akira/Documents/GitHub/Twitch-Based-Muscle-Model/Development_Code';
data_folder = '/Users/akira/Documents/GitHub/Twitch-Based-Muscle-Model/Model Parameters/Model_11';

for i = 91:100
    i 
    cd('/Users/akira/Documents/Github/Twitch-Based-Muscle-Model/Development_Code/Data')
    load(['Data_temp_' num2str(i)])
    cd(code_folder)

    CT = Data{2,1}
    t2t = Data{2,5}
    min_fusion = min(Data{2,11})
    figure()
    plot(Data{2,9},Data{2,11})
    xlim([0 3])
    %hold on 
    
end